version: "3.8"
services:
  app:
    image: mlopsdemo/housing-api:latest
    container_name: housing-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app
    environment:
      - LOG_PATH=/app/api.log
      - DB_PATH=/app/api_requests.db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana-data:
