version: "3.8"
services:
  app:
    image: mlopsdemo/housing-api:latest
    container_name: housing-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/mlflow/mlruns
    environment:
      - LOG_PATH=/app/logs/api.log
      - DB_PATH=/app/logs/api_requests.db
      - MLFLOW_TRACKING_URI=file:/mlflow/mlruns

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    container_name: mlflow
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow.db:/mlflow.db
      - ./models:/models
      - ./mlruns:/mlflow/mlruns
    working_dir: /mlflow
    command: mlflow ui --backend-store-uri sqlite:///mlflow.db --default-artifact-root file:/mlflow/mlruns --host 0.0.0.0 --port 5000
    environment:
      - MLFLOW_TRACKING_URI=file:/mlflow/mlruns

volumes:
  grafana-data:
