global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/prometheus.rules.yml

scrape_configs:
  - job_name: "housing-api"
    static_configs:
      - targets: ["app:8000"]
        labels:
          job: "housing-api"

