name: CI/CD Deploy to EC2 with Monitoring

on:
  push:
    branches: [ mlops ]
  workflow_dispatch:

jobs:
  build-train-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install base tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[s3]" flake8

      - name: Lint
        run: flake8 src/

      # --- DVC: pull from S3 and materialize per dvc.lock ---
      - name: Configure AWS creds (for DVC S3)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: DVC pull & checkout data
        run: |
          rm -f data/california_housing.csv || true
          dvc pull -v
          dvc checkout -v
          ls -lh data/ || true

      # --- Build image FIRST (used for training + serving) ---
      - name: Build image
        run: |
          docker build -t mlopsdemo/housing-api:${{ github.sha }} -t mlopsdemo/housing-api:latest .

      # --- Wait for MLflow tracking server on EC2 (use POST /experiments/search) ---
      - name: Wait for MLflow server (EC2:5000)
        env:
          MLFLOW_HOST: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          for i in {1..30}; do
            if curl -s -X POST "http://${MLFLOW_HOST}:5000/api/2.0/mlflow/experiments/search" \
                 -H 'Content-Type: application/json' -d '{}' >/dev/null; then
              echo "MLflow is up"; exit 0
            fi
            echo "Waiting for MLflow... ($i/30)"; sleep 2
          done
          echo "MLflow not reachable"; exit 1

      # --- Train & log to EC2 MLflow server (no local mlruns mount) ---
      - name: Train and log models to MLflow server
        env:
          MLFLOW_TRACKING_URI: http://${{ secrets.EC2_PUBLIC_IP }}:5000
          GIT_PYTHON_REFRESH: quiet
        run: |
          docker run --rm \
            -e MLFLOW_TRACKING_URI="${MLFLOW_TRACKING_URI}" \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/models:/app/models \
            mlopsdemo/housing-api:${{ github.sha }} \
            python src/train.py

      # --- DVC: Track the deployed model and push to S3 ---
      - name: Ensure DVC remote points to S3 prefix
        run: |
          dvc remote list || dvc remote add -d myremote s3://mlops-grp13/mlops-app
          dvc remote modify myremote url s3://mlops-grp13/mlops-app

      - name: DVC-track deployed model & push
        run: |
          test -f models/best_model.pkl || (echo "models/best_model.pkl missing" && ls -la models/ && exit 1)
          dvc add models/best_model.pkl
          dvc push -v
          git add models/best_model.pkl.dvc
          test -f dvc.lock && git add dvc.lock || true

      - name: Commit model pointer (.dvc) back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(dvc): track best_model.pkl in S3 via DVC"
          commit_user_name: ci-bot
          commit_user_email: ci-bot@example.com
          push_options: --force-with-lease

      # --- Push images to Docker Hub ---
      - name: Docker Hub login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push images
        run: |
          docker push mlopsdemo/housing-api:${{ github.sha }}
          docker push mlopsdemo/housing-api:latest

      # --- Deploy to EC2 ---
      - name: Prepare .env
        run: echo "GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" > .env

      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_deploy_key
          chmod 600 ec2_deploy_key

      - name: Rsync code to EC2
        run: |
          rsync -az -e "ssh -o StrictHostKeyChecking=no -i ec2_deploy_key" . ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_PUBLIC_IP }}:/home/${{ secrets.EC2_SSH_USER }}/mlops-app/

      - name: Compose up on EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_USER: ${{ secrets.EC2_SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_deploy_key $EC2_SSH_USER@$EC2_PUBLIC_IP << 'EOF'
            set -e
            cd ~/mlops-app
            docker pull mlopsdemo/housing-api:latest
            if command -v docker-compose >/dev/null 2>&1; then
              COMPOSE="docker-compose"
            elif docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              echo "Docker Compose not installed"; exit 1
            fi
            $COMPOSE down || true
            $COMPOSE up -d --remove-orphans
            docker ps
          EOF

      - name: Cleanup key
        run: rm -f ec2_deploy_key
