name: CI/CD Deploy to EC2 with Monitoring

on:
  push:
    branches: [mlops, mlops-part2]
  workflow_dispatch:
  


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check and start EC2 instance if stopped
        run: |
          INSTANCE_ID="${{ secrets.EC2_INSTANCE_ID }}"
          INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
          
          if [ "$INSTANCE_STATE" = "stopped" ]; then
            echo "EC2 instance is stopped. Starting it..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID
            echo "Waiting for instance to be running..."
            aws ec2 wait instance-running --instance-ids $INSTANCE_ID
            echo "Instance is now running!"
          elif [ "$INSTANCE_STATE" = "running" ]; then
            echo "EC2 instance is already running"
          else
            echo "Instance state: $INSTANCE_STATE"
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 src/ --max-line-length=150

      - name: Build, tag, and push Docker image to Docker Hub
        run: |
          docker build -t mlopsdemo/housing-api:latest .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push mlopsdemo/housing-api:latest

      - name: Create .env for Docker Compose
        run: |
          echo "GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" > .env

      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_deploy_key
          chmod 600 ec2_deploy_key

      - name: Copy code and .env to EC2
        run: |
          rsync -az -e "ssh -o StrictHostKeyChecking=no -i ec2_deploy_key" . ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_PUBLIC_IP }}:/home/${{ secrets.EC2_SSH_USER }}/mlops-app/
          ssh -o StrictHostKeyChecking=no -i ec2_deploy_key ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_PUBLIC_IP }} "cd mlops-app && ls -al .env"

      - name: Remote deploy on EC2 (docker-compose up)
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_USER: ${{ secrets.EC2_SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_deploy_key $EC2_SSH_USER@$EC2_PUBLIC_IP << EOF
            cd mlops-app
            docker pull mlopsdemo/housing-api:latest
            docker-compose down || true
            docker-compose up -d --remove-orphans
          EOF

      - name: Cleanup SSH key
        run: rm -f ec2_deploy_key
